### ISSUE TITLE
Finetune models do not load custom weights

### ISSUE THREAD

**Issue by Johansmm** [Visual-Behavior/aloception#88]
Given that all finetune models load theirs specific weights and then remove the last layer, If we want to load a custom weights from a specific file, always these models will "delete" the last layer. For this purpouse, the only way is create the model an then, use the `load_weight` function. Example:

```
from alonet.detr import DetrR50Finetune
from alonet.common.weights import load_weights

# it is expected to load the weights of the route, but as the last layer is removed, the weights are loaded without any sense.
model = DetrR50Finetune(num_classes=250, "/path/panoptic/weights.pth")

# Right way by the moment (expected result):
model = DetrR50Finetune(num_classes=250)
load_weights(model, "/path/panoptic/weights.pth",model_detr.device,)
```

**Comment by thibo73800** [comment]
Yeah, for me `DetrR50Finetune`is always supposed to load the pre-trained weights. There the following do not make sense:

```python
model = DetrR50Finetune(num_classes=250, weights="detr-r50")
```

But the following should work 
```python
model = DetrR50Finetune(num_classes=250, "/path/panoptic/weights.pth")
```

Internally it should look something like that 

```python
class DetrR50Finetune(Detrr50):

    def __init__(self, weights=None):
        super().__init__(weights="detr-r50")
        self.custom_layer = ...
        if weights is not None: load_weights(weights)
```

Also we have to think about one specific issue that might happens if someone want to reuse a pretrained finetune model DetrR50Finetune trained with X classes to continue training on Y classes. If this is the case, the above code might not work.  The only pretty way I see right now is to have the possibility to create the model like so:

```python
model = DetrR50Finetune(num_classes=250, base_weights="/path/panoptic/weights.pth")
```
for loading the weights before creating the top layer OR

```
model = DetrR50Finetune(num_classes=250, weights="/path/panoptic/weights.pth")
```
for loading the weights after creating the new top layer

It would look something like this:

```python
class DetrR50Finetune(Detrr50):

    def __init__(self, base_weights=None, weights=None):
        super().__init__(weights="detr-r50")
        if base_weights is not None: load_weights(base_weights)
        self.custom_layer = ...
        if weights is not None: load_weights(weights)
```
What do you think ?

**Comment by Johansmm** [comment]
I like it. But maybe, if you agree with me, we can use as default `base_weights="detr-r50` and  simply do:

```
class DetrR50Finetune(Detrr50):

    def __init__(self, base_weights="detr-r50", weights=None):
        super().__init__(weights=base_weights))
        self.custom_layer = ...
        if weights is not None: load_weights(weights)
```

As long as it is clear that the default weight base to be used will be detr-r50. This would allow (if any user wanted) to train from scratch (I don't see the point but I think it could happen). Let me know what you think of the idea @thibo73800

**Comment by thibo73800** [comment]
Yes agree ! @Johansmm
